theme: jekyll-theme-minimal
google_analytics: UA-189500722-1
title: Takanori Horibe
description: This is a summary of the activities.
# show_downloads: false
logo: /assets/img/icon.JPG

source: .
layouts_dir: _layouts
includes_dir: _includes
show_excerpts: true