theme: jekyll-theme-minimal
google_analytics: 
title: TAGUSARI Yuya
description: This is a summary of the activities.
# show_downloads: false

# 写真のディレクトリは
logo: /assets/icon.jpg

source: .
layouts_dir: _layouts
includes_dir: _includes
show_excerpts: true
